package:
  name: args
  version: 6.2.0

source:
  git_url: https://github.com/Taywee/args.git
  git_rev: 6.2.0

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.

